/* DO NOT EDIT | Generated by gyro */

import RealmSwift

final class Address: Object {

  enum Attributes: String {
    case city = "city"
    case state = "state"
    case street = "street"
  }

  dynamic var city: String?
  dynamic var state: String?
  dynamic var street: String?

}
