/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Person: Object {

  enum Attributes: String {
    case firstName = "firstName"
    case lastName = "lastName"
  }

  enum Relationships: String {
    case address = "address"
    case phones = "phones"
  }

  dynamic var firstName: String = ""
  dynamic var lastName: String = ""
  dynamic var address: Address?
  let phones = List<Phone>()

}
