/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Phone: Object {

  enum Attributes: String {
    case model = "model"
    case name = "name"
  }


  dynamic var model: String = ""
  var modelEnum: PhoneModel? {
    get {
      guard let enumValue = PhoneModel(rawValue: model) else { return nil }
      return enumValue
    }
    set { model = newValue?.rawValue ?? "" }
  }

  dynamic var name: String = ""

}
