/* DO NOT EDIT | Generated by gyro */

import RealmSwift

final class Phone: Object {

  enum Attributes: String {
    case model = "model"
    case name = "name"
  }


  dynamic var model: String?
  var modelEnum: PhoneModel? {
    get {
      guard let model = model,
        let enumValue = PhoneModel(rawValue: model)
        else { return nil }
      return enumValue
    }
    set { model = newValue?.rawValue ?? nil }
  }

  dynamic var name: String?

}
