/* DO NOT EDIT | Generated by gyro */

enum PhoneModel: String {
  case iPhone = "iPhone"
  case iPhone3G = "iPhone3G"
  case iPhone3GS = "iPhone3GS"
  case iPhone4 = "iPhone4"
  case iPhone4s = "iPhone4s"
  case iPhone5 = "iPhone5"
  case iPhone5c = "iPhone5c"
  case iPhone5s = "iPhone5s"
  case iPhoneSE = "iPhoneSE"
  case iPhone6 = "iPhone6"
  case iPhone6Plus = "iPhone6Plus"
  case iPhone6s = "iPhone6s"
  case iPhone6sPlus = "iPhone6sPlus"
  case iPhone7 = "iPhone7"
  case iPhone7Plus = "iPhone7Plus"
  case iPhone8 = "iPhone8"
  case iPhone8Plus = "iPhone8Plus"
  case iPhoneX = "iPhoneX"
}
